---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lyrics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lyrics-service
  template:
    metadata:
      labels:
        app: lyrics-service
    spec:
      containers:
        - name: lyrics-service
          image: lyrics-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: lyrics-service
spec:
  selector:
    app: lyrics-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: composition-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composition-service
  template:
    metadata:
      labels:
        app: composition-service
    spec:
      containers:
        - name: composition-service
          image: composition-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: composition-service
spec:
  selector:
    app: composition-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: analytics-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete-service
  template:
    metadata:
      labels:
        app: delete-service
    spec:
      containers:
        - name: delete-service
          image: delete-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5006
---
apiVersion: v1
kind: Service
metadata:
  name: lyrics-service
spec:
  selector:
    app: lyrics-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: orchestrator:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
spec:
  type: NodePort
  selector:
    app: orchestrator
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
